name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=7q(6=lj)x(-6iv)f#y9bsrjsb=&9b)*rffhlg7z@2km#u1$&c5
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=nP2M7bNqbXH2AkGqRWa4YWE6
      - PASSAGE_API_KEY=irF5tPxanO.CwaxWnd5XcDieraOpjkHtsItXeL2SsgeT2mb7SUS30kcz7l193aFfFe7vzwZ65Ah
    ports:
      - 8000:8000 